name: Grid Masters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.2.2
        host: linux
        target: desktop

    - name: Build project using qmake
      run: |
        cd build
        qmake ..
        make VERBOSE=1

    - name: Run application (if applicable)
      run: |
        cd build
        ./Tic-Tac-Toe

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.2.2
        host: linux
        target: desktop

    - name: Build tests
      run: |
        mkdir -p build_tests
        cd build_tests
        qmake ../tests/Tic-Tac-Toe_tests.pro
        make

    - name: Run tests
      run: |
        cd build_tests
        ./Tic-Tac-Toe_tests
