name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.2.2
        host: linux
        target: desktop

    - name: Build application
      run: |
        cd build
        qmake ..
        make VERBOSE=1

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.2.2
        host: linux
        target: desktop

    - name: Build tests
      run: |
        cd tests
        mkdir -p build
        cd build
        qmake ../Tic-Tac-Toe_tests.pro
        make

    - name: Run tests
      run: |
        cd tests/build
        ./Tic-Tac-Toe_tests
